export const NOTIFICATION_MODULE_TYPE = {
  TASK_MANAGER: 'TASK_MANAGER',
  FORMS: 'FORMS',
  CONTACT: 'CONTACT',
  USER: 'USER'
}

export const TASK_MANAGER_NOTIFICATION_ACTION = {
  TASK_CREATION: 'TASK_CREATION',
  TASK_UPDATE: 'TASK_UPDATE',
  ADD_NEW_TASK_COMMENT: 'ADD_NEW_TASK_COMMENT'
}

export const FORMS_NOTIFICATION_ACTION = {
  CONTACT_CREATION: 'CONTACT_CREATION'
}

export const USER_NOTIFICATION_ACTION = {
  CREATE: 'CREATE'
}
